# Generated by Django 5.1.6 on 2025-03-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='can_be_edited',
            new_name='is_system',
        ),
    ]
