# Generated by Django 5.1.7 on 2025-03-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_rename_can_be_edited_collection_is_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='films',
            field=models.ManyToManyField(related_name='collections', to='collection.film'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
